env:
  aseApiKeyId: 6Q3W37Y8XIDPGEKX06ASNM7PZR87EX0V
  aseApiKeySecret: O2VUV2HXKU92Y27OE1HNRR147VP9CCWI
  compiledArtifactFolder: none
  scanConfig: Normal scan
  aseAppName: $(Build.Repository.Name)
  aseHostname: winappscan.lab.local
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  sevSecGw: highIssues
  maxIssuesAllowed: 100
  WorkingDirectory: $GITHUB_WORKSPACE
  BuildNumber: $(Build.BuildNumber)

name: SAST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: SAST
        shell: pwsh
        run: |
          $Env:WorkingDirectory
          $Env:GITHUB_WORKSPACE
