env:
  aseApiKeyId: xxxxxxxxxxxxxxxx
  aseApiKeySecret: xxxxxxxxxxxxxxxx
  compiledArtifactFolder: none
  scanConfig: Normal scan
  aseAppName: $(Build.Repository.Name)
  aseHostname: xxxxxxxxxxxxxxxx
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  sevSecGw: highIssues
  maxIssuesAllowed: 100
  WorkingDirectory: ${GITHUB_WORKSPACE}
  BuildNumber: $(Build.BuildNumber)

name: SAST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: SAST
        shell: pwsh
        run: |
          echo ${env:WorkingDirectory}
